title: <p align="center"> Kishore Chandra Sekhar Kandukuri </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/kishore-kandukuri-267493217/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
    I'm working as a Software Engineer in Zebra Technologies in RFID Domain and I am currently learning about the AI and ML concepts very eager to contribute with my skills.
  <br>
  </p>



theme: jekyll-theme-minimal
